name: Bootstrap

on: [workflow_dispatch, push]

jobs:
  build:
      runs-on: ubuntu-latest
      container: ghcr.io/fix-project/wasm_toolchain_docker:latest
      steps:
      - name: "checkout repository"
        uses: "actions/checkout@v4"
        with:
          submodules: 'recursive'
      - name: install deps
        run: sudo apt update && sudo apt-get install libboost-all-dev libgoogle-glog-dev software-properties-common -y
      - name: install g++ 13
        run: sudo add-apt-repository 'ppa:ubuntu-toolchain-r/test' && sudo apt update && sudo apt-get install gcc-13 g++-13 -y
      - shell: bash
        run: 'echo HOME=/home | sudo tee -a $GITHUB_ENV'
      - name: cmake-build
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=MinSizeRel -DCMAKE_C_COMPILER=gcc-13 -DCMAKE_CXX_COMPILER=g++-13
      - name: compile-build
        run: cmake --build build --parallel 8
      - name: cmake-fix-build
        run: cmake -S . -B fix-build -DBUILD_SYS_DRIVER:BOOL=OFF -DCMAKE_BUILD_TYPE=MinSizeRel
      - name: compile-fix-build
        run: cmake --build fix-build --parallel 8
      - name: build
        shell: bash
        run: |
          chmod +x build.sh
          ./build.sh 2
      - name: serialize
        shell: bash
        run: |
          chmod +x serialize.sh
          ./serialize.sh
      - name: Upload bootstrap artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bootstrap
          path: |
            ./.fix/
          if-no-files-found: error

  # release:
  #     if: startsWith(github.ref, 'refs/tags/')
  #     needs: ['build']
  #     runs-on: ubuntu-latest
  #     steps:
  #     - name: "checkout repository"
  #       uses: "actions/checkout@v2"
  #       with:
  #         submodules: 'recursive'
  #     - name: Download artifact
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: bootstrap
  #     - name: install zip
  #       run: sudo apt install zip -y
  #     - name: Create release asset
  #       run: zip -r bootstrap .fix
  #     - name: Show structure
  #       run: ls -R
  #     - name: Release
  #       uses: softprops/action-gh-release@v1
  #       with:
  #         files: bootstrap.zip
